[package]
name = "bring-your-own-memory-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8"
critical-section = "1.1"

[dev-dependencies]
critical-section = { version = "1.1", features = ["std"]}
